name: Bundle On Commit
on:
  push:
    branches:
      - master
      - main

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Bundle
        run: |
          npm install
          npm run release

      - name: Commit
        run: |
          git add -f schemas
          git commit -m "Bundle On Commit"
          git push --force origin HEAD:main
