name: release on tag

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  release-on-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Install pnpm based on `packageManager` in package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Install Node.js
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Bundle JSON Schemas
        run: pnpm install && pnpm run release

      - name: Github Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          make_latest: true
          files: |
            schemas/*

      - name: NPM Release
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit Changes
        run: |
          git commit --allow-empty -am 'ci: release ${{ github.ref_name }}'
          git push origin HEAD:main
